-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.anotacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid NOT NULL,
  titulo character varying NOT NULL,
  descricao text,
  criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT anotacoes_pkey PRIMARY KEY (id),
  CONSTRAINT anotacoes_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.ativacoes_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid NOT NULL,
  tipo character varying,
  item_id uuid NOT NULL,
  nome_item character varying,
  ativo boolean,
  mana_gasta integer,
  estamina_gasta integer,
  criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ativacoes_log_pkey PRIMARY KEY (id),
  CONSTRAINT ativacoes_log_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.campanha_personagens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campanha_id uuid NOT NULL,
  personagem_id uuid NOT NULL,
  jogador_id uuid NOT NULL,
  adicionado_em timestamp without time zone DEFAULT now(),
  CONSTRAINT campanha_personagens_pkey PRIMARY KEY (id),
  CONSTRAINT campanha_personagens_campanha_id_fkey FOREIGN KEY (campanha_id) REFERENCES public.campanhas(id),
  CONSTRAINT campanha_personagens_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id),
  CONSTRAINT campanha_personagens_jogador_id_fkey FOREIGN KEY (jogador_id) REFERENCES public.perfis(id)
);
CREATE TABLE public.campanha_turnos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campanha_id uuid NOT NULL,
  numero_turno integer NOT NULL DEFAULT 1,
  criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  passado_por uuid NOT NULL,
  CONSTRAINT campanha_turnos_pkey PRIMARY KEY (id),
  CONSTRAINT campanha_turnos_campanha_id_fkey FOREIGN KEY (campanha_id) REFERENCES public.campanhas(id),
  CONSTRAINT campanha_turnos_passado_por_fkey FOREIGN KEY (passado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.campanhas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  narrador_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  codigo character varying NOT NULL UNIQUE,
  ativa boolean DEFAULT true,
  criada_em timestamp without time zone DEFAULT now(),
  atualizada_em timestamp without time zone DEFAULT now(),
  turno_atual integer DEFAULT 0,
  dia_atual integer DEFAULT 1,
  calendario_obs jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT campanhas_pkey PRIMARY KEY (id),
  CONSTRAINT campanhas_narrador_id_fkey FOREIGN KEY (narrador_id) REFERENCES auth.users(id)
);
CREATE TABLE public.comentarios_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  texto text NOT NULL,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  score integer DEFAULT 0,
  CONSTRAINT comentarios_posts_pkey PRIMARY KEY (id),
  CONSTRAINT comentarios_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.perfis(id),
  CONSTRAINT comentarios_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.conhecimentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid,
  nome text NOT NULL,
  descricao text,
  tipo text,
  nivel integer DEFAULT 1,
  criado_em timestamp without time zone DEFAULT now(),
  atualizado_em timestamp without time zone DEFAULT now(),
  bonus jsonb DEFAULT '[]'::jsonb,
  ativa boolean DEFAULT true,
  ativada_em timestamp without time zone,
  dados jsonb,
  CONSTRAINT conhecimentos_pkey PRIMARY KEY (id),
  CONSTRAINT conhecimentos_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.habilidades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid,
  nome text NOT NULL,
  descricao text,
  tipo text DEFAULT 'habilidade'::text CHECK (tipo = ANY (ARRAY['habilidade'::text, 'modulo'::text])),
  nivel integer DEFAULT 0,
  custo_mana integer DEFAULT 0,
  dano text DEFAULT 0,
  cooldown integer DEFAULT 0,
  criado_em timestamp without time zone DEFAULT now(),
  atualizado_em timestamp without time zone DEFAULT now(),
  custo_estamina integer DEFAULT 0,
  efeito text,
  bonus jsonb DEFAULT '[]'::jsonb,
  ativa boolean DEFAULT true,
  ativada_em timestamp without time zone,
  duracao_turnos integer DEFAULT 0,
  turnos_restantes integer DEFAULT 0,
  turno_ativacao integer,
  deativada_em timestamp with time zone,
  dados jsonb,
  CONSTRAINT habilidades_pkey PRIMARY KEY (id),
  CONSTRAINT habilidades_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.inventario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid NOT NULL,
  nome character varying NOT NULL,
  quantidade integer NOT NULL DEFAULT 1,
  descricao text,
  peso numeric NOT NULL DEFAULT 0,
  criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  atualizado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  bonus jsonb DEFAULT '[]'::jsonb,
  ativa boolean DEFAULT true,
  ativada_em timestamp without time zone,
  turno_ativacao integer,
  duracao_turnos integer,
  turnos_restantes integer,
  deativada_em timestamp with time zone,
  dados jsonb,
  CONSTRAINT inventario_pkey PRIMARY KEY (id),
  CONSTRAINT inventario_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.magias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  personagem_id uuid,
  nome text NOT NULL,
  elemento text,
  descricao text,
  dano text DEFAULT 0,
  custo_mana integer DEFAULT 0,
  nivel integer DEFAULT 0,
  criado_em timestamp without time zone DEFAULT now(),
  atualizado_em timestamp without time zone DEFAULT now(),
  custo_estamina integer DEFAULT 0,
  efeito text,
  bonus jsonb DEFAULT '[]'::jsonb,
  ativa boolean DEFAULT true,
  ativada_em timestamp without time zone,
  turno_ativacao integer,
  duracao_turnos integer,
  turnos_restantes integer,
  deativada_em timestamp with time zone,
  dados jsonb,
  CONSTRAINT magias_pkey PRIMARY KEY (id),
  CONSTRAINT magias_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id)
);
CREATE TABLE public.perfis (
  id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  bio text,
  avatar_url text,
  nivel_conta integer DEFAULT 1,
  experiencia integer DEFAULT 0,
  idioma_preferido text DEFAULT 'pt'::text,
  criado_em timestamp without time zone DEFAULT now(),
  atualizado_em timestamp without time zone DEFAULT now(),
  CONSTRAINT perfis_pkey PRIMARY KEY (id),
  CONSTRAINT perfis_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.personagens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  idade integer CHECK (idade >= 0),
  raca text,
  altura numeric,
  peso numeric,
  foto text,
  forca_base integer DEFAULT 0,
  forca_bonus integer DEFAULT 0,
  forca_total integer DEFAULT (forca_base + forca_bonus),
  agilidade_base integer DEFAULT 0,
  agilidade_bonus integer DEFAULT 0,
  agilidade_total integer DEFAULT (agilidade_base + agilidade_bonus),
  sorte_base integer DEFAULT 0,
  sorte_bonus integer DEFAULT 0,
  sorte_total integer DEFAULT (sorte_base + sorte_bonus),
  inteligencia_base integer DEFAULT 0,
  inteligencia_bonus integer DEFAULT 0,
  inteligencia_total integer DEFAULT (inteligencia_base + inteligencia_bonus),
  foco_base integer DEFAULT 0,
  foco_bonus integer DEFAULT 0,
  foco_total integer DEFAULT (foco_base + foco_bonus),
  arcanismo_base integer DEFAULT 0,
  arcanismo_bonus integer DEFAULT 0,
  arcanismo_total integer DEFAULT (arcanismo_base + arcanismo_bonus),
  reputacao text,
  nivel integer DEFAULT 0,
  vida_atual integer DEFAULT 0,
  vida_maxima integer DEFAULT 0,
  estamina_atual integer DEFAULT 0,
  estamina_maxima integer DEFAULT 0,
  mana_atual integer DEFAULT 0,
  mana_maxima integer DEFAULT 0,
  pontos_totais_atributo integer DEFAULT 0,
  pontos_totais_status integer DEFAULT 0,
  pontos_restantes integer DEFAULT 0,
  passiva text,
  criado_em timestamp without time zone DEFAULT now(),
  atualizado_em timestamp without time zone DEFAULT now(),
  perfil_id uuid NOT NULL,
  passiva_bonus jsonb DEFAULT '[]'::jsonb,
  vida_maxima_bonus integer DEFAULT 0,
  mana_maxima_bonus integer DEFAULT 0,
  estamina_maxima_bonus integer DEFAULT 0,
  esquiva_bonus integer DEFAULT 0,
  acerto_bonus integer DEFAULT 0,
  passivas_ativas jsonb DEFAULT '[]'::jsonb,
  ultimo_turno_processado integer DEFAULT 0,
  foto_url text,
  CONSTRAINT personagens_pkey PRIMARY KEY (id),
  CONSTRAINT fk_personagem_perfil FOREIGN KEY (perfil_id) REFERENCES public.perfis(id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tipo character varying NOT NULL DEFAULT 'outro'::character varying CHECK (tipo::text = ANY (ARRAY['homebrew'::character varying, 'personagem'::character varying, 'mundo'::character varying, 'narrativa'::character varying, 'outro'::character varying]::text[])),
  titulo character varying NOT NULL,
  conteudo text NOT NULL,
  personagem_id uuid,
  campanha_id uuid,
  score integer NOT NULL DEFAULT 0,
  destacado_semana boolean NOT NULL DEFAULT false,
  destacado_mes boolean NOT NULL DEFAULT false,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.perfis(id),
  CONSTRAINT posts_personagem_id_fkey FOREIGN KEY (personagem_id) REFERENCES public.personagens(id),
  CONSTRAINT posts_campanha_id_fkey FOREIGN KEY (campanha_id) REFERENCES public.campanhas(id)
);
CREATE TABLE public.votos_comentarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  comentario_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tipo_voto smallint NOT NULL CHECK (tipo_voto = ANY (ARRAY[1, '-1'::integer])),
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT votos_comentarios_pkey PRIMARY KEY (id),
  CONSTRAINT votos_comentarios_comentario_id_fkey FOREIGN KEY (comentario_id) REFERENCES public.comentarios_posts(id),
  CONSTRAINT votos_comentarios_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.votos_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tipo_voto smallint NOT NULL CHECK (tipo_voto = ANY (ARRAY[1, '-1'::integer])),
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT votos_posts_pkey PRIMARY KEY (id),
  CONSTRAINT votos_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.perfis(id),
  CONSTRAINT votos_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);