-- ============================================
-- CORRIGIR TIPOS DE CAMPOS PARA ACEITAR DADOS (1d6, 2d8, etc)
-- ============================================

-- 1. ALTERAR CAMPO PODER_BASE EM MAGIAS DE INTEGER PARA TEXT
ALTER TABLE magias 
ALTER COLUMN poder_base TYPE TEXT;

-- 2. ALTERAR CAMPO DANO EM HABILIDADES DE INTEGER PARA TEXT
ALTER TABLE habilidades 
ALTER COLUMN dano TYPE TEXT;

-- 3. REMOVER RESTRIÇÃO NOT NULL SE EXISTIR (OPCIONAL)
ALTER TABLE magias 
ALTER COLUMN poder_base DROP NOT NULL;

ALTER TABLE habilidades 
ALTER COLUMN dano DROP NOT NULL;

-- 4. ADICIONAR VALORES PADRÃO SE NECESSÁRIO
ALTER TABLE magias 
ALTER COLUMN poder_base SET DEFAULT '0';

ALTER TABLE habilidades 
ALTER COLUMN dano SET DEFAULT '0';
