-- ============================================
-- SQL: ADICIONAR SISTEMA DE TURNOS EM CAMPANHAS
-- ============================================

-- 1. CRIAR TABELA DE TURNOS DE CAMPANHA
CREATE TABLE IF NOT EXISTS campanha_turnos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campanha_id UUID NOT NULL REFERENCES campanhas(id) ON DELETE CASCADE,
    numero_turno INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    passado_por UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. ADICIONAR COLUNA DE TURNO ATUAL NAS CAMPANHAS
ALTER TABLE campanhas ADD COLUMN IF NOT EXISTS turno_atual INTEGER DEFAULT 0;

-- 3. CRIAR ÍNDICES PARA PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_campanha_turnos_campanha ON campanha_turnos(campanha_id);
CREATE INDEX IF NOT EXISTS idx_campanha_turnos_numero ON campanha_turnos(numero_turno);

-- 4. ADICIONAR COLUNAS DE RASTREAMENTO NAS HABILIDADES (se não existirem)
ALTER TABLE habilidades ADD COLUMN IF NOT EXISTS turno_ativacao INTEGER;
ALTER TABLE habilidades ADD COLUMN IF NOT EXISTS duracao_turnos INTEGER;
ALTER TABLE habilidades ADD COLUMN IF NOT EXISTS turnos_restantes INTEGER;

-- 5. ADICIONAR COLUNAS DE RASTREAMENTO NAS MAGIAS
ALTER TABLE magias ADD COLUMN IF NOT EXISTS turno_ativacao INTEGER;
ALTER TABLE magias ADD COLUMN IF NOT EXISTS duracao_turnos INTEGER;
ALTER TABLE magias ADD COLUMN IF NOT EXISTS turnos_restantes INTEGER;

-- 6. ADICIONAR COLUNAS DE RASTREAMENTO NO INVENTÁRIO (ITENS)
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS turno_ativacao INTEGER;
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS duracao_turnos INTEGER;
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS turnos_restantes INTEGER;

-- 7. ADICIONAR COLUNA DE RASTREAMENTO DE TURNO NA TABELA PERSONAGENS
ALTER TABLE personagens ADD COLUMN IF NOT EXISTS ultimo_turno_processado INTEGER DEFAULT 0;
